name: 1 - Test Pull Request

on:
  pull_request:
  workflow_run:
    workflows: [ "0 - Create Pull Request to Main" ]
    types: [ completed ]

jobs:
  cayena-pull-request:
    uses: Poupachef/cayena-github-actions/.github/workflows/pull-request-template.yml@main
    secrets: inherit
